id: P8445FB4E
initial_creation_type: input
source_metadata:
  title: Compendium of Sādhanas
  language: fr
  description: 'Texts belonging to (and related to) the Compendium of Sādhanas (sgrub
    thabs kun btus), a collection originally compiled by Jamyang Khyentse Wangpo (1820–1892)
    and later supplemented by Jamyang Loter Wangpo (1847–1914). Note that the volume
    numbers below correspond to the fourteen-volume Derge edition (reproduced by Dzongsar
    Institute):'
  volume:
    b051d31c34924603949fc4b6e4d00ae1:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Volume One
    f6bb8daf2b2c4630aae95b25ace2095f:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Volume One
    50371206cf914848a885c72f2217e15f:
      title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the
        Profound Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
      parent: Volume Two
    4ac033787de8428796826f39f0e054ba:
      title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of
        Great Compassion & Mahāmudrā in Union'
      parent: Volume Three
    79a57e3e1efa47b0b4b957b869b2077a:
      title: Concise Seven-Heap Maṇḍala Offering
      parent: Volume Three
    82aa38918a69436c99a778c7cfd24de3:
      title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha
        Thangtong Gyalpo's Lifetime as Bhikṣu Padma Karpo
      parent: Volume Three
    217fd6343f4743ca92d0bb409e80e7ae:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Volume Twelve
    6a42a4f0d0e74573a60bbc69f21827d7:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Volume Thirteen
    e4999f7f07ae434ab64a02fa34a5f97c:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Volume Thirteen
    354d8f3b5e5146449d8419bf3ce60b9b:
      title: An Aspiration Prayer
      parent: Volume Fourteen
    350776de4c084f23846ad6b8fc76b221:
      title: Prayer for Dispelling Famine
      parent: Volume Fourteen
    022c0955927b491b9c1fa1ae7f907d96:
      title: Prayer of Truthful Words to Pacify the Fear of War
      parent: Volume Fourteen
    7e60745d3f044a2d9d2dfae1cd5fb5c7:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Volume Fourteen
created_at: '2022-03-01T03:15:47.011252'
last_modified_at: '2022-03-01T03:15:47.011254'
